/** @format */
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import SnackbarProvider from "@/context/SnackbarContext";
import { ThemeProvider } from "@mui/material/styles";
import theme from "@/theme";
import Provider from "../lib/react-query/Provider";
import "./globals.css";
import AppIntro from "@/components/atoms/AppIntro";
// import { CssVarsProvider } from "@mui/material/styles";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Provider>
          <AppRouterCacheProvider>
            <SnackbarProvider>
              <ThemeProvider theme={theme}>
                <AppIntro />
                {children}
              </ThemeProvider>
            </SnackbarProvider>
          </AppRouterCacheProvider>
        </Provider>
      </body>
    </html>
  );
}
